version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.0.3
  eb: circleci/aws-elastic-beanstalk@1.0.0
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - node/install-yarn
      - checkout
      -aws-cli/setup
      -eb/setup
      # install dependencies in both apps
      # install server dependencies
      # install UI dependencies
      # Build server
      # Build UI
      - run:
          name: Back-End Install
          command: |
            yarn backend:install
      - run:
          name: Front-End Install
          command: |
            yarn frontend:install
      - run:
          name: Back-End Build
          command: |
            yarn backend:build
      - run:
          name: Front-End Build
          command: |
            yarn frontend:build
